language: python
services:
  - redis-server
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5"
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.5"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.7"
      env: DJANGO="django>=1.5,<2.0"
install:
  - pip install $DJANGO
  - pip install -q redis
script: python setup.py nosetests
